# Un Ejemplo As칤ncrono

Implementemos un m칩dulo que obtenga datos de usuario de una API y devuelva el nombre de usuario.

游늮`models/user.js`
```js
import request from '@/services/request';

export function getUserName(userID) {
  return request(`/users/${userID}`).then(user => user.name);
}
```

En la implementaci칩n anterior, esperamos que el m칩dulo `request.js` devuelva una promesa. Encadenamos una llamada a `then` para recibir el nombre de usuario.

Ahora imagine una implementaci칩n de `request.js` que va a la red y obtiene algunos datos del usuario:

游늮`services/request.js`
```js 
import http from 'http'

export default function request(url) {
  return new Promise(resolve => {
    // This is an example of an http request, for example to fetch
    // user data from an API.
    // This module is being mocked in 'services/__mocks__/request.js'
    http.get({path: url}, response => {
      let data = '';
      response.on('data', _data => (data += _data));
      response.on('end', () => resolve(data));
    });
  });
}
```

Debido a que no queremos ir a la red en nuestra prueba, vamos a crear una simulaci칩n manual para nuestro m칩dulo `request.js` en la carpeta `__mocks__` (la carpeta distingue entre may칰sculas y min칰sculas, `__MOCKS__` no funcionar치). Podr칤a verse algo como esto:

游늮`services/__mocks__/request.js`
```js
const users = {
  4: {name: 'Mark'},
  5: {name: 'Paul'},
};

export default function request(url) {
  return new Promise((resolve, reject) => {
    const userID = parseInt(url.substr('/users/'.length), 10);
    process.nextTick(() =>
      users[userID]
        ? resolve(users[userID])
        : reject({
            error: `User with ${userID} not found.`,
          }),
    );
  });
}
```

Ahora escribamos una prueba para nuestra funcionalidad as칤ncrona.

游늮`tests/models/user.spec.js`
```js
vi.mock('@/services/request');
import * as user from '@/models/user';

// The assertion for a promise must be returned.
it('works with promises', () => {
  expect.assertions(1);
  return user.getUserName(4).then(data => expect(data).toEqual('Mark'));  
});
```

Llamamos a `vi.mock('@/services/request')` para decirle a Vitest que use nuestro simulacro manual. `it` espera que el valor de retorno sea una _**Promise**_ que se va a resolver. Puede encadenar tantas _**Promises**_ como desee y llamar a `expect` en cualquier momento, siempre que devuelva una _**Promise**_ al final.

## `.resolves`

Hay una forma menos detallada de usar `resolves` para desenvolver el valor de una promesa cumplida junto con cualquier otro comparador. Si la promesa es rechazada, la afirmaci칩n fallar치.

```js
it('works with resolves', () => {  
  expect.assertions(1);
  return expect(user.getUserName(5)).resolves.toEqual('Paul');
});
```

## `async`/`await`
Tambi칠n es posible escribir pruebas utilizando la sintaxis `async`/`await`. As칤 es como escribir칤as los mismos ejemplos de antes:

```js
// async/await can be used.
it('works with async/await', async () => {
  expect.assertions(1);
  const data = await user.getUserName(4);
  expect(data).toEqual('Mark');
});

// async/await can also be used with `.resolves`.
it('works with async/await and resolves', async () => {
  expect.assertions(1);
  await expect(user.getUserName(5)).resolves.toEqual('Paul');
});
```

## Manejo de errores

Los errores se pueden manejar usando el m칠todo `.catch`. Aseg칰rese de agregar `expect.assertions` para verificar que se llame a un cierto n칰mero de afirmaciones. De lo contrario, una promesa cumplida no fallar칤a la prueba:

```js
// Testing for async errors using Promise.catch.
it('tests error with promises', () => {
  expect.assertions(1);
  return user.getUserName(2).catch(e =>
    expect(e).toEqual({
      error: 'User with 2 not found.',
    }),
  );
});

// Or using async/await.
it('tests error with async/await', async () => {
  expect.assertions(1);
  try {
    await user.getUserName(1);
  } catch (e) {
    expect(e).toEqual({
      error: 'User with 1 not found.',
    });
  }
});
```

## `.rejects`

El ayudante .`rejects` funciona como el ayudante `.resolves`. Si se cumple la promesa, la prueba fallar치 autom치ticamente. `expect.assertions(number)` no es necesario, pero se recomienda para verificar que se llama a un cierto n칰mero de [afirmaciones](https://vitest.dev/api/#expect-assertions) durante una prueba. De lo contrario, es f치cil olvidar a `return`/`await` las afirmaciones `.resolves`.

```js
// Testing for async errors using `.rejects`.
it('tests error with rejects', () => {
  expect.assertions(1);
  return expect(user.getUserName(3)).rejects.toEqual({
    error: 'User with 3 not found.',
  });
});

// Or using async/await with `.rejects`.
it('tests error with async/await and rejects', async () => {
  expect.assertions(1);
  await expect(user.getUserName(3)).rejects.toEqual({
    error: 'User with 3 not found.',
  });
});
```

El c칩digo de este ejemplo est치 disponible en [ejemplos/as칤ncronos](https://github.com/facebook/jest/tree/main/examples/async).

Si desea probar los temporizadores, como setTimeout, eche un vistazo a la documentaci칩n de las [Simulaciones de Temporizador](../vitest/simulaciones-de-temporizador.html).
